Repository cepdnaclk/e18-co227-Auto-Marking-and-Student-Performance-Analyser-System-for-Continuous-Assessments-Group-A, pull requests merged in 2022-07, with the labels that each got.

#34 Save assignment marks into a file
  Project/functions/index.js
  Project/functions/package-lock.json
  Project/functions/package.json
  Project/functions/public/web4/examples/assignment.html
  Project/functions/public/web4/examples/students.html
Labels: enhancement

#37 Completed the download option
  Project/functions/public/web4/examples/Assignment1.xlsx
  Project/functions/public/web4/examples/Assignment2.xlsx
  Project/functions/public/web4/examples/Assignment3.xlsx
  Project/functions/public/web4/examples/Assignment4.xlsx
Labels: enhancement

#40 fixed bugs in performane view
  Project/functions/public/web4/examples/Assign1.xlsx
  Project/functions/public/web4/examples/Assignment1.xlsx
  Project/functions/public/web4/examples/Assignment2.xlsx
  Project/functions/public/web4/examples/Assignment3.xlsx
  Project/functions/public/web4/examples/Assignment4.xlsx
  Project/functions/public/web4/examples/profile.html
  Project/functions/public/web4/examples/students.html
Labels: bug

#42 complete the uploader
  Project/functions/index.js
  Project/functions/package-lock.json
  Project/functions/package.json
  Project/functions/public/web4/examples/Assignment2.xlsx
  Project/functions/public/web4/examples/Assignment3.xlsx
  Project/functions/public/web4/examples/Assignment4.xlsx
  Project/functions/public/web4/examples/SampleStudent.xlsx
  Project/functions/public/web4/examples/students.html
  node_modules/.package-lock.json
  node_modules/busboy/.eslintrc.js
  node_modules/busboy/.github/workflows/ci.yml
  node_modules/busboy/.github/workflows/lint.yml
  node_modules/busboy/LICENSE
  node_modules/busboy/README.md
  node_modules/busboy/bench/bench-multipart-fields-100mb-big.js
  node_modules/busboy/bench/bench-multipart-fields-100mb-small.js
  node_modules/busboy/bench/bench-multipart-files-100mb-big.js
  node_modules/busboy/bench/bench-multipart-files-100mb-small.js
  node_modules/busboy/bench/bench-urlencoded-fields-100pairs-small.js
  node_modules/busboy/bench/bench-urlencoded-fields-900pairs-small-alt.js
  node_modules/busboy/lib/index.js
  node_modules/busboy/lib/types/multipart.js
  node_modules/busboy/lib/types/urlencoded.js
  node_modules/busboy/lib/utils.js
  node_modules/busboy/package.json
  node_modules/busboy/test/common.js
  node_modules/busboy/test/test-types-multipart-charsets.js
  node_modules/busboy/test/test-types-multipart-stream-pause.js
  node_modules/busboy/test/test-types-multipart.js
  node_modules/busboy/test/test-types-urlencoded.js
  node_modules/busboy/test/test.js
  node_modules/streamsearch/.eslintrc.js
  node_modules/streamsearch/.github/workflows/ci.yml
  node_modules/streamsearch/.github/workflows/lint.yml
  node_modules/streamsearch/LICENSE
  node_modules/streamsearch/README.md
  node_modules/streamsearch/lib/sbmh.js
  node_modules/streamsearch/package.json
  node_modules/streamsearch/test/test.js
  package-lock.json
  package.json
Labels: enhancement

#45 Complete the student add process with a file ,tested and fix bugs
  Project/functions/public/web4/examples/Assignment1.xlsx
  Project/functions/public/web4/examples/Assignment2.xlsx
  Project/functions/public/web4/examples/Assignment3.xlsx
  Project/functions/public/web4/examples/Assignment4.xlsx
  Project/functions/public/web4/examples/students.html
  Project/functions/public/web4/examples/uploadFiles/1657107928139.xlsx
Labels: bug, enhancement

#46 fix a bug
  Project/functions/index.js
  Project/functions/package-lock.json
  Project/functions/package.json
  Project/functions/public/web4/examples/assignment.html
Labels: bug

#50 Added display label how the assign progress is going on
  Project/functions/public/web4/examples/profile.html
Labels: enhancement

#52 Complete email sending and multiline test cases
  Project/functions/index.js
  Project/functions/public/web4/examples/assignment.html
  Project/functions/public/web4/examples/before_Login/About.html
  Project/functions/public/web4/examples/before_Login/Contact.html
  Project/functions/public/web4/examples/before_Login/WhatIS.html
Labels: enhancement

#54 Add lecturer and instructor separation, user can login as lectirer or instructor and each have different capabilities
  Project/functions/auth.js
  Project/functions/index.js
  Project/functions/package-lock.json
  Project/functions/package.json
  Project/functions/public/web4/examples/dashboard.html
  Project/functions/public/web4/examples/instructorDetails.html
  Project/functions/public/web4/examples/sign-in.html
  Project/functions/public/web4/examples/sign-up.html
Labels: enhancement

#56 Marks table, Profile updated
  Project/functions/index.js
  Project/functions/package-lock.json
  Project/functions/public/web4/examples/assignment.html
  Project/functions/public/web4/examples/profile.html
  Project/functions/public/web4/examples/students.html
Labels: bug

#57 Deadline prob fixed. Can view which assign are expired for each student. Finalized to some level
  Project/functions/index.js
  Project/functions/public/web4/examples/Course.html
  Project/functions/public/web4/examples/assignment.html
  Project/functions/public/web4/examples/assignmentDetails.html
  Project/functions/public/web4/examples/profile.html
  Project/functions/public/web4/examples/students.html
Labels: enhancement

#58 Add Google Signin to the system
  Project/functions/index.js
  Project/functions/public/web4/examples/before_Login/About.html
  Project/functions/public/web4/examples/before_Login/Contact.html
  Project/functions/public/web4/examples/before_Login/WhatIS.html
  Project/functions/public/web4/examples/profile.html
  Project/functions/public/web4/examples/sign-in.html
Labels: enhancement
